"""DevBar-Release-only steps run ADVISORY while a ratification window is open (WI-336).

Owner ruling 2026-07-27, made on measured cost: an open `Drafted`/`Modified`
window drops the derived gate, and the plan then drops every step tagged for the
higher gate — so `lint`, `dupes` and `--require-verified` STOP RUNNING. That is
a blind spot, not a lower bar. Twelve commits went green over those steps during
the 2026-07-26/27 window; 20 ruff findings and 86 duplicate blocks surfaced in
one lump when it closed (WI-333 / WI-334).

(That is the ruling as made, and it is kept verbatim because it is the reason
these guards exist. The `dupes` step named in it no longer exists — D-7/WI-426
tore the duplication census down — so the assertions below pin `lint` plus a
surviving declared `[step:]` instead. The ruling is about the blind spot, not
about which steps happened to fall into it.)

The trigger is deliberately narrow, and these guards pin that: the steps run
advisory only when the gate was **suppressed by a window**, which
`derive_gate.py` records as `drafted=`/`modified=` in the `# basis:` comment. A
project genuinely at DevBar-Reqs has not earned those steps and must not be nagged by
them on every run — a warn tier nobody wants is a warn tier everybody learns to
ignore.
"""

import re

from conftest import ROOT, SCRIPTS, load_script, run_py

check = load_script("check")

GATE_WINDOW = """\
# DERIVED GATE — generated by scripts/derive_gate.py (do not hand-edit).
# basis: SN=1 SR=2 LLR=2 TC=2 drafted=0 modified=7 computed=DevBar-Tests phase=1 per-phase=1=DevBar-Tests
DevBar-Tests
"""
# A MATURE repo opening a new phase: phase 4 has drafts (DevBar-Below) while 1-3 stayed at
# DevBar-Release. The drafts are holding a spine that has demonstrably earned the higher bar.
GATE_DRAFT_MATURE = GATE_WINDOW.replace(
    "drafted=0 modified=7 computed=DevBar-Tests phase=1 per-phase=1=DevBar-Tests",
    "drafted=3 modified=0 computed=DevBar-Below phase=4 per-phase=1=DevBar-Release;2=DevBar-Release;3=DevBar-Release;4=DevBar-Below",
)
# A GENUINELY EARLY project: drafts, and nothing has ever climbed. Ordinary DevBar-Below/DevBar-Reqs
# state, NOT a window (127-REVIEW-A MAJOR 5).
GATE_DRAFT_EARLY = GATE_WINDOW.replace(
    "drafted=0 modified=7 computed=DevBar-Tests phase=1 per-phase=1=DevBar-Tests",
    "drafted=1 modified=0 computed=DevBar-Below phase=1 per-phase=1=DevBar-Below",
)
# Drafts with no phase breakdown at all: ambiguous, so treated as ordinary.
GATE_DRAFT_UNPHASED = GATE_WINDOW.replace(
    "drafted=0 modified=7 computed=DevBar-Tests phase=1 per-phase=1=DevBar-Tests",
    "drafted=2 modified=0 computed=DevBar-Below phase=(none) per-phase=(none)",
)
# STILL an early project: phase 1 has only reached DevBar-Reqs while phase 2 is drafted.
# Some phase IS above `computed`, but nothing has reached the DevBar-Tests/DevBar-Release bar the
# advisory tier reports on (128-REVIEW-A MAJOR 3).
GATE_DRAFT_EARLY_MULTIPHASE = GATE_WINDOW.replace(
    "drafted=0 modified=7 computed=DevBar-Tests phase=1 per-phase=1=DevBar-Tests",
    "drafted=1 modified=0 computed=DevBar-Below phase=2 per-phase=1=DevBar-Reqs;2=DevBar-Below",
)
GATE_CLEAN = GATE_WINDOW.replace("drafted=0 modified=7", "drafted=0 modified=0")
GATE_HAND_WRITTEN = "# a hand-maintained gate file, no derivation basis\nG2\n"

# --- WI-341: the `ex-draft` basis field ---------------------------------------
# The fixtures above carry NO `ex-draft=`, so every assertion made on them also
# pins the LEGACY path — a gate file written before WI-341 keeps its old
# behaviour until it is regenerated. The ones below carry the field.
#
# A mature SINGLE-phase repo reopened by one Drafted. This is the case the
# per-phase heuristic structurally could not see (128-REVIEW-A MAJOR 3): the
# Drafted drops the only phase to DevBar-Below, so `per-phase=1=DevBar-Below` is indistinguishable
# from a brand-new project — while `ex-draft=DevBar-Release` says plainly that everything
# the draft did not touch is still at DevBar-Release.
GATE_DRAFT_MATURE_SINGLE_PHASE = GATE_WINDOW.replace(
    "drafted=0 modified=7 computed=DevBar-Tests phase=1 per-phase=1=DevBar-Tests",
    "drafted=1 modified=0 computed=DevBar-Below ex-draft=DevBar-Release phase=1 per-phase=1=DevBar-Below",
)
# Byte-identical except for `ex-draft`: an early project's ratified rows are
# undecomposed, so removing the drafts recovers nothing.
GATE_DRAFT_EARLY_EX = GATE_DRAFT_MATURE_SINGLE_PHASE.replace(
    "ex-draft=DevBar-Release", "ex-draft=DevBar-Reqs"
)
# Drafts present, but they are not what is holding the gate down (something else
# is already at DevBar-Tests) — nothing is being suppressed, so it is not a window.
GATE_DRAFT_NOT_SUPPRESSING = GATE_WINDOW.replace(
    "drafted=0 modified=7 computed=DevBar-Tests phase=1 per-phase=1=DevBar-Tests",
    "drafted=1 modified=0 computed=DevBar-Tests ex-draft=DevBar-Tests phase=1 per-phase=1=DevBar-Tests",
)


def _gate(tmp_path, text, name="gate"):
    p = tmp_path / name
    p.write_text(text, encoding="utf-8")
    return p


def test_window_open_detects_either_kind_of_pending_row(tmp_path):
    # A `Modified` row is conclusive on its own: the state is DEFINED as a
    # post-attestation amendment, so it cannot exist before ratification.
    assert check.window_open(_gate(tmp_path, GATE_WINDOW, "a")) is True
    # Drafts are only a window when some phase sits ABOVE the computed level —
    # i.e. the spine has climbed and the drafts are holding it down.
    assert check.window_open(_gate(tmp_path, GATE_DRAFT_MATURE, "b")) is True
    # The negative halves, which are the whole point of the narrow trigger:
    # a settled spine gets no advisory pass...
    assert check.window_open(_gate(tmp_path, GATE_CLEAN, "c")) is False
    # ...a gate file with no derivation basis expresses NO opinion rather than
    # guessing (a hand-maintained or pre-derived file must not start nagging)...
    assert check.window_open(_gate(tmp_path, GATE_HAND_WRITTEN, "d")) is False
    # ...and a repo with no gate file at all is not a window.
    assert check.window_open(tmp_path / "does-not-exist") is False


def test_ordinary_early_drafting_is_not_a_ratification_window(tmp_path):
    """127-REVIEW-A MAJOR 5, pinned.

    The first cut returned True for any `drafts>0`, which is ORDINARY DevBar-Below/DevBar-Reqs
    state — so a project that had never ratified anything was told about DevBar-Tests/DevBar-Release
    steps on every run, exactly the nagging the docstring claimed to avoid. The
    discriminator is whether any phase has climbed above the computed level.

    Both negatives matter: an early project, and an unphased repo where the
    breakdown cannot answer the question and the conservative reading wins.
    """
    assert check.window_open(_gate(tmp_path, GATE_DRAFT_EARLY, "early")) is False
    assert check.window_open(_gate(tmp_path, GATE_DRAFT_UNPHASED, "unphased")) is False
    # ...and the case the first fix still got wrong: a phase above `computed` is
    # not enough, it must have reached the DevBar-Tests/DevBar-Release bar the advisory tier reports.
    assert (
        check.window_open(_gate(tmp_path, GATE_DRAFT_EARLY_MULTIPHASE, "early2"))
        is False
    )
    # ...while the mature-repo-new-phase case, which differs ONLY in the
    # per-phase field, is still detected. Without this pair the fix could be
    # "return False for drafts" and look correct.
    assert check.window_open(_gate(tmp_path, GATE_DRAFT_MATURE, "mature")) is True


def test_a_single_phase_repo_reopened_by_a_draft_is_a_window(tmp_path):
    """128-REVIEW-A MAJOR 3, the residual FALSE NEGATIVE — now closed (WI-341).

    A Drafted added to a previously-mature single-phase repo dropped that phase to
    DevBar-Below. The per-phase rule then found no phase above `computed` and reported no
    window, so `lint`, `dupes` and `--require-verified` stopped running for the
    duration — precisely the blind spot the advisory tier exists to close,
    reopened by one row. `ex-draft` answers the question the breakdown could
    not: what the spine computes with the drafts removed.

    The three fixtures differ ONLY in `ex-draft=`/`computed=`, so a fix that
    just returned True for drafts would fail the second and third.
    """
    assert (
        check.window_open(_gate(tmp_path, GATE_DRAFT_MATURE_SINGLE_PHASE, "reopened"))
        is True
    )
    # Same shape, nothing hidden behind the drafts: an early project.
    assert check.window_open(_gate(tmp_path, GATE_DRAFT_EARLY_EX, "early-ex")) is False
    # Drafts that are not suppressing anything: ex-draft == computed.
    assert (
        check.window_open(_gate(tmp_path, GATE_DRAFT_NOT_SUPPRESSING, "nosuppress"))
        is False
    )
    # The mutation proof, in the suite rather than in a session transcript: strip
    # ONLY `ex-draft=DevBar-Release` from the winning fixture and the answer reverts to the
    # documented defect. So this guard cannot pass for any reason other than the
    # field being read — and the legacy fallback is pinned to its old behaviour
    # at the same time.
    without = GATE_DRAFT_MATURE_SINGLE_PHASE.replace("ex-draft=DevBar-Release ", "")
    assert "ex-draft" not in without
    assert check.window_open(_gate(tmp_path, without, "legacy")) is False


def test_ex_draft_overrides_the_per_phase_fallback(tmp_path):
    """`ex-draft` is the authority when present; per-phase is only the fallback.

    Pinned with the two fields DISAGREEING in both directions, because the
    fallback is now unreachable code for any current gate file and a wrong
    precedence would be invisible otherwise.
    """
    # per-phase says "mature" (1=DevBar-Release above computed), ex-draft says nothing is
    # hidden. ex-draft wins: not a window.
    misleading_phase = GATE_WINDOW.replace(
        "drafted=0 modified=7 computed=DevBar-Tests phase=1 per-phase=1=DevBar-Tests",
        "drafted=1 modified=0 computed=DevBar-Below ex-draft=DevBar-Below phase=4 per-phase=1=DevBar-Release;4=DevBar-Below",
    )
    assert check.window_open(_gate(tmp_path, misleading_phase, "mp")) is False
    # And the reverse: per-phase sees nothing, ex-draft sees DevBar-Release. Window.
    misleading_flat = GATE_WINDOW.replace(
        "drafted=0 modified=7 computed=DevBar-Tests phase=1 per-phase=1=DevBar-Tests",
        "drafted=1 modified=0 computed=DevBar-Below ex-draft=DevBar-Release phase=1 per-phase=(none)",
    )
    assert check.window_open(_gate(tmp_path, misleading_flat, "mf")) is True


def test_the_meta_repos_own_gate_file_carries_the_field(tmp_path):
    """Not a fixture test: the real docs/gate must actually publish `ex-draft`.

    Without this, every assertion above could pass against hand-written strings
    while `derive_gate.py` published nothing and the consumer silently ran on
    the legacy fallback forever.
    """
    basis = (ROOT / "docs" / "gate").read_text(encoding="utf-8")
    assert re.search(r"#\s*basis:.*\bex-draft=DevBar-\w+\b", basis), basis


def test_advisory_steps_are_the_ones_a_higher_gate_requires():
    """The selection rule itself, over the real step table.

    At DevBar-Tests with a window, the advisory set is what a higher gate requires and
    this run is not already doing. Note what is deliberately NOT asserted any
    more: that no name appears in both tiers. It legitimately can — `traceability`
    runs at DevBar-Tests *and* DevBar-Release with different commands, and the DevBar-Release form is the one the
    owner ruled in. The no-duplication property is asserted at COMMAND level by
    `test_a_step_that_is_identical_at_both_gates_is_not_run_twice`; the old
    name-level version of it is what entrenched BLOCKER 4."""
    # The REAL profile: `doc-refs`/`figures`/`module-coverage` are docs/stack.ini
    # `[step:]` sections, so a None profile would silently drop them and this guard
    # would assert against a smaller table than the harness actually runs. (`dupes`
    # was the original such step; D-7/WI-426 deleted it, so the declared set this
    # exercises is now the three above.)
    profile = check.load_profile(ROOT / "docs" / "stack.ini")
    all_steps = check.steps(80, "all", "DevBar-Tests", None, profile)
    plan = [s for s in all_steps if "DevBar-Tests" in s[3]]
    # Call `advisory_plan` rather than restating its filter. The first version of
    # this test re-implemented the selection rule, so it asserted against its own
    # copy and would have passed against any implementation — the same
    # cannot-observe-what-it-names shape as the other vacuous guards this session
    # produced. `window_open` is patched because the real repo has no open
    # window, and the SELECTION is what is under test here, not the trigger.
    real_window_open = check.window_open
    check.window_open = lambda *a, **k: True
    try:
        advisory = check.advisory_plan(
            "DevBar-Tests", plan, lambda g: check.steps(80, "all", g, None, profile)
        )
    finally:
        check.window_open = real_window_open
    advisory_names = {s[0] for s in advisory}

    # The steps the ruling was about are recovered. `dupes` was named in the
    # ruling too and is no longer assertable — D-7/WI-426 deleted the step — so
    # `doc-refs` stands in for the declared-[step:] half of the claim, which is
    # what would regress if extra_steps stopped feeding the advisory selection.
    assert {"lint", "doc-refs"} <= advisory_names, advisory_names
    assert len(advisory_names) >= 3, advisory_names
    # The exclusion asserted as BEHAVIOUR, not as a constant. Asserting only
    # `"tests+coverage" in ADVISORY_EXCLUDE` passes even when the filter ignores
    # the set entirely — proven by mutation: deleting the `not in
    # ADVISORY_EXCLUDE` clause left every other assertion here green.
    assert "tests+coverage" not in advisory_names, advisory_names
    # ...and its consumer went with it: `module-coverage` grades the report only
    # `tests+coverage` writes (127-REVIEW-A MAJOR 6).
    assert "module-coverage" not in advisory_names, advisory_names


def test_the_stronger_traceability_variant_is_what_runs_advisory():
    """127-REVIEW-A BLOCKER 4, pinned by the COMMAND and not the step name.

    `traceability` runs at DevBar-Tests *and* DevBar-Release, so a name-level check says nothing: the
    first cut selected steps the current gate did not require, which excluded
    `traceability` outright and therefore ran `--require-verified` NOWHERE — and
    the test asserted that absence, entrenching it. What the owner ruled in was
    the DevBar-Release CRITERION, so that is what this asserts: the advisory tier carries a
    traceability command containing `--require-verified`, and the gating one
    does not.
    """
    profile = check.load_profile(ROOT / "docs" / "stack.ini")
    all_steps = check.steps(80, "all", "DevBar-Tests", None, profile)
    plan = [s for s in all_steps if "DevBar-Tests" in s[3]]
    real_window_open = check.window_open
    check.window_open = lambda *a, **k: True
    try:
        advisory = check.advisory_plan(
            "DevBar-Tests", plan, lambda g: check.steps(80, "all", g, None, profile)
        )
    finally:
        check.window_open = real_window_open

    gating_trace = [s for s in plan if s[0] == "traceability"]
    advisory_trace = [s for s in advisory if s[0] == "traceability"]
    assert gating_trace, "no gating traceability step — fixture is wrong"
    assert not any("--require-verified" in s[2] for s in gating_trace), (
        "DevBar-Tests's own traceability already carries --require-verified, so this test "
        "cannot observe the advisory tier adding it"
    )
    assert advisory_trace, (
        "the DevBar-Release traceability variant does not run at all — the exact defect "
        "BLOCKER 4 named. Advisory steps were: {}".format([s[0] for s in advisory])
    )
    assert any("--require-verified" in s[2] for s in advisory_trace), [
        s[2] for s in advisory_trace
    ]


def test_a_step_that_is_identical_at_both_gates_is_not_run_twice():
    """The other half of building from the higher gate's table: only a step whose
    COMMAND differs may appear in both tiers. Without this, every DevBar-Tests step would
    be re-run advisory at DevBar-Release and the summary would double."""
    profile = check.load_profile(ROOT / "docs" / "stack.ini")
    all_steps = check.steps(80, "all", "DevBar-Tests", None, profile)
    plan = [s for s in all_steps if "DevBar-Tests" in s[3]]
    real_window_open = check.window_open
    check.window_open = lambda *a, **k: True
    try:
        advisory = check.advisory_plan(
            "DevBar-Tests", plan, lambda g: check.steps(80, "all", g, None, profile)
        )
    finally:
        check.window_open = real_window_open
    gating_cmds = {(s[0], tuple(s[2])) for s in plan}
    dupes = [s[0] for s in advisory if (s[0], tuple(s[2])) in gating_cmds]
    assert not dupes, "these run identically in both tiers: {}".format(dupes)
    # And no advisory step is listed twice in its own tier.
    keys = [(s[0], tuple(s[2])) for s in advisory]
    assert len(keys) == len(set(keys)), keys


def test_advisory_output_is_marked_as_not_gating(tmp_path):
    """A warn tier that prints a bare `FAIL` is how a non-gating step gets read
    as the bar. The summary line must say so on the same line."""
    source = (SCRIPTS / "check.py").read_text(encoding="utf-8")
    assert "[advisory — not gating]" in source
    # ...and the banner must state the exit code is unaffected, because that is
    # the claim a reader needs before they decide to ignore a line.
    assert "the exit code is not affected" in source


def test_the_expensive_step_is_excluded_and_says_why():
    """`tests+coverage` must NOT join the advisory pass.

    It is the one DevBar-Release step that is not a blind spot — the commit bar runs the
    suite directly — and including it would re-run the whole suite plus coverage
    on every gate run for the life of a window (measured 55.8 s at the smoke
    tier, ~11 min unfiltered). A warn tier that doubles every run is one people
    route around, which costs more than it catches.

    Pinned by name because an exclusion is a hole in the coverage this ruling
    just created: if a future edit drops the reason, this fails and the next
    author has to restate it."""
    assert "tests+coverage" in check.ADVISORY_EXCLUDE
    source = (SCRIPTS / "check.py").read_text(encoding="utf-8")
    assert "is NOT a blind spot" in source
    # The negative half: the exclusion list is a scalpel, not a bucket — the
    # steps the ruling was actually about must never be in it.
    assert not ({"lint", "doc-refs"} & check.ADVISORY_EXCLUDE)


WINDOW_GATE = (
    "# DERIVED GATE — generated by scripts/derive_gate.py\n"
    "# basis: SN=1 SR=1 LLR=1 TC=1 drafted=0 modified={} computed=DevBar-Tests phase=1\n"
    "DevBar-Tests\n"
)
CANARY_STEP = (
    "\n[step:always-fails]\n"
    "command = {py} -c \"import sys; print('ADVISORY-CANARY'); sys.exit(1)\"\n"
    "gates = DevBar-Release\n"
)


def test_an_advisory_failure_does_not_change_the_exit_code(scaffold):
    """The load-bearing claim, driven end to end.

    Everything above asserts selection and wording. This asserts the ONE thing
    the ruling promises: a step that FAILS in the advisory pass is reported and
    does not change the run's outcome. "Warn-only" is a property of the exit
    code, and no amount of string-matching in the source can observe it.

    Measures the GATING FAILURE COUNT, not just the exit code: a bare scaffold
    is not green at DevBar-Tests (it fails derived-gate/traceability/design-flows on
    placeholder registries), so `exit 0` would be testing the fixture and
    exit-code EQUALITY is blind — 1 == 1 whether or not the advisory step
    gated. The count moves the moment an advisory failure is counted as a real
    one, which is precisely the regression this guards. Approved by mutation:
    letting `advisory_results` feed `failed` takes it 3 -> 4."""
    docs = scaffold / "docs"
    (docs / "gate").write_text(WINDOW_GATE.format(4), encoding="utf-8")
    args = ["scripts/check.py", "--gate", "DevBar-Tests", "--tier", "smoke"]

    def gating_failures(proc):
        text = proc.stdout + proc.stderr
        m = re.search(r"RESULT: FAIL \((\d+) step\(s\) failed\)", text)
        return int(m.group(1)) if m else 0  # PASS = zero gating failures

    baseline = run_py(args, cwd=scaffold)

    stack = (docs / "stack.ini").read_text(encoding="utf-8")
    (docs / "stack.ini").write_text(stack + CANARY_STEP, encoding="utf-8")
    withcanary = run_py(args, cwd=scaffold)
    out = withcanary.stdout + withcanary.stderr

    assert "ADVISORY-CANARY" in out, "the advisory step never ran:\n" + out
    assert "advisory — not gating" in out, out
    assert gating_failures(withcanary) == gating_failures(baseline), (
        "a FAILING advisory step was counted as a gating failure ({} -> {}):"
        "\n{}".format(gating_failures(baseline), gating_failures(withcanary), out)
    )
    assert withcanary.returncode == baseline.returncode, out

    # The negative half: close the window and that same failing step must vanish
    # entirely — not run, not reported — or this is a permanent warn tier rather
    # than a window-scoped one.
    (docs / "gate").write_text(WINDOW_GATE.format(0), encoding="utf-8")
    closed = run_py(args, cwd=scaffold)
    assert "ADVISORY-CANARY" not in (closed.stdout + closed.stderr)


def test_list_shows_the_advisory_tier_it_will_run(scaffold):
    """`--list` must print what the invocation WILL do, both tiers.

    128-REVIEW-A MINOR 5: with a real window open, `--list` printed only the
    weaker gating traceability command while the same invocation went on to
    execute the stronger advisory one. An option that says "print the plan" and
    hides half the plan is worse than no option.

    Driven through the real CLI on a scaffold, because the defect was in
    `main()`'s early return, which no unit-level call to `advisory_plan` can
    observe.
    """
    docs = scaffold / "docs"
    (docs / "gate").write_text(WINDOW_GATE.format(4), encoding="utf-8")
    listed = run_py(
        ["scripts/check.py", "--gate", "DevBar-Tests", "--tier", "smoke", "--list"],
        cwd=scaffold,
    )
    out = listed.stdout + listed.stderr
    assert "Advisory during the open ratification window" in out, out
    assert "NOT gating" in out, out
    # The load-bearing half: the stronger command is VISIBLE, not just the label.
    assert "--require-verified" in out, out

    # The negative half: close the window and the advisory section disappears,
    # so this is a window-scoped disclosure and not permanent noise.
    (docs / "gate").write_text(WINDOW_GATE.format(0), encoding="utf-8")
    closed = run_py(
        ["scripts/check.py", "--gate", "DevBar-Tests", "--tier", "smoke", "--list"],
        cwd=scaffold,
    )
    assert "Advisory during the open" not in (closed.stdout + closed.stderr)
