"""The monotonic product-regression floor (WI-473, repo review 2026-08-19 C-01).

The derived bar is a MIN over every in-scope spine row, so ONE ordinary draft
requirement drops a mature project to what a fresh scaffold displays — and the
shipped downstream workflow (`ci/check.yml`) runs `check.py` at exactly that
value on every push and pull request. Artifact maturity and product regression
were riding one reversible number: drafting a requirement says nothing at all
about whether the code that already exists still builds, lints and passes.

So `check.py` grows a second, DERIVED value beside the honest one — the shape
process.md §4 pre-authorizes ("if a monotonic reading is wanted it is a second,
derived high-water number shown BESIDE the honest one, never instead") — and
product-LAYER steps are selected at `max(derived bar, ex-draft)`.

The design record, including why `ex-draft` beats a stored high-water mark and
what "monotonic" is and is not being claimed here:
docs/plans/2026-08-20-product-regression-floor.md.
"""

from conftest import ROOT, SCRIPTS, load_script, make_minimal_project, run_py

check = load_script("check")
derive_gate = load_script("derive_gate")

# A mature spine held down by one draft: `computed` is below the ladder while
# `ex-draft` — the same arithmetic with the pending rows removed — still reads
# the bar the ratified rows earned.
GATE_MATURE = (
    "# DERIVED BAR — generated by scripts/derive_gate.py (do not hand-edit).\n"
    "# basis: SN=1 SR=2 LLR=2 TC=2 drafted=1 computed=DevStg-Below "
    "ex-draft=DevStg-Tests phase=1 per-phase=1=DevStg-Below\n"
    "DevStg-Reqs\n"
)
# Byte-identical but for the one field: an early project's ratified rows are
# undecomposed, so removing the drafts recovers nothing to hold.
GATE_EARLY = GATE_MATURE.replace("ex-draft=DevStg-Tests", "ex-draft=DevStg-Reqs")
# A gate file written before WI-341 added the field, and a hand-maintained one.
GATE_NO_FIELD = GATE_MATURE.replace("ex-draft=DevStg-Tests ", "")
GATE_HAND_WRITTEN = "# a hand-maintained gate file, no derivation basis\nDevStg-Reqs\n"

CANARY_PRODUCT = (
    "\n[step:product-canary]\n"
    "command = {py} -c \"print('PRODUCT-CANARY')\"\n"
    "gates = DevStg-Tests\n"
    "layer = product\n"
)


def _gate(tmp_path, text, name="gate"):
    p = tmp_path / name
    p.write_text(text, encoding="utf-8")
    return p


def _steps_at(gate):
    return check.steps("coverage.json", "smoke", gate, None, None)


def test_the_floor_reads_ex_draft_and_abstains_wherever_it_cannot_know(tmp_path):
    """The value, and — more important — the four ways it declines to have one.

    A floor that GUESSES is worse than no floor: it would manufacture a bar out
    of a file that never claimed one, and the first thing anyone would learn is
    to distrust it. Every abstention below is a file that cannot answer the
    question, not a file that answers "low"."""
    assert check.product_floor(_gate(tmp_path, GATE_MATURE, "a")) == "DevStg-Tests"
    assert check.product_floor(_gate(tmp_path, GATE_EARLY, "b")) == "DevStg-Reqs"
    # Pre-WI-341 cache: the field is absent, so the file predates the question.
    assert check.product_floor(_gate(tmp_path, GATE_NO_FIELD, "c")) is None
    # No `# basis:` line at all — a hand-set gate has no derivation to read.
    assert check.product_floor(_gate(tmp_path, GATE_HAND_WRITTEN, "d")) is None
    # A below-the-ladder sentinel is NOT floored up to DevStg-Reqs the way the
    # runnable value is: a floor must never be minted from a level the spine has
    # not shown. Same for a value this build does not recognize.
    below = GATE_MATURE.replace("ex-draft=DevStg-Tests", "ex-draft=DevStg-Below")
    assert check.product_floor(_gate(tmp_path, below, "e")) is None
    bogus = GATE_MATURE.replace("ex-draft=DevStg-Tests", "ex-draft=DevStg-Banana")
    assert check.product_floor(_gate(tmp_path, bogus, "f")) is None
    assert check.product_floor(tmp_path / "nope") is None


def _profile_with(tmp_path, *extra_steps):
    """This repo's stack profile plus declared `[step:*]` sections.

    Both floor-selection tests need a product step the floor CAN hold, and the
    repo's own profile has none — so they build one the way the documentation
    tells an adopter to, and read it back through the real loader rather than
    hand-constructing a step tuple."""
    stack = tmp_path / "stack.ini"
    stack.write_text(
        (ROOT / "docs" / "stack.ini").read_text(encoding="utf-8")
        + "".join(extra_steps),
        encoding="utf-8",
    )
    return check.load_profile(stack)


# A product step at BOTH bars — so it is in the DevStg-Reqs gating plan already
# AND in the DevStg-Tests table the floor asks for. Exactly the shape that makes
# the dedup guard load-bearing.
CANARY_BOTH_BARS = (
    "\n[step:product-both]\n"
    "command = {py} -c \"print('BOTH-BARS')\"\n"
    "gates = DevStg-Reqs DevStg-Tests\n"
    "layer = product\n"
)


def test_the_floor_holds_product_steps_and_never_process_ones(tmp_path):
    """The TWO AXES, which is the whole design — asserted in both directions.

    The positive half alone would pass a floor that simply re-ran the higher
    bar's entire plan, which is not a floor but a bar that ignores its own
    derivation. The negative half is what makes it a separation: a maturity
    check MUST still fall when the spine's maturity falls, because that fall is
    the new-phase signal the derived value exists to give.

    THE POSITIVE HALF IS NOW ACTUALLY THERE (2026-08-21 review, M-9). Over this
    repo's own profile `held` is EMPTY — every product-layer step in the kit is
    tagged `{DevStg-Impl}` only, which the floor can never select (see the
    dormancy test below) — so `layers <= {"product"}` read `set() <= {...}` and
    the third assertion ran over an empty set. Three of the five tests in this
    file survived deleting the feature outright. The fixture below declares the
    product step an adopter would, which is also the only configuration in
    which this mechanism is live anywhere today."""
    profile = _profile_with(tmp_path, CANARY_PRODUCT)

    def steps_at(gate):
        return check.steps("coverage.json", "smoke", gate, None, profile)

    gate = "DevStg-Reqs"
    plan = [s for s in steps_at(gate) if gate in s[3]]
    held = check.floor_plan(gate, plan, "DevStg-Tests", steps_at)
    assert [s[0] for s in held] == ["product-canary"], (
        "the floor held nothing, so every assertion below is vacuous: {}".format(held)
    )
    layers = {s[4] for s in held}
    assert layers <= {"product"}, "the floor reached a process step: {}".format(held)
    # `traceability` is the control: a process step the DevStg-Tests table
    # carries and the DevStg-Reqs plan does not. It must stay dropped.
    tests_bar = {s[0] for s in steps_at("DevStg-Tests") if "DevStg-Tests" in s[3]}
    assert "traceability" in tests_bar
    assert "traceability" not in {s[0] for s in held}


def test_the_floor_never_runs_a_step_twice(tmp_path):
    """The floor promotes; the advisory tier reports. A step must not do both.

    These two mechanisms answer the same suppression from opposite directions
    (WI-336's warn-only tier, and this bar-holding one), so the failure mode is
    a step that runs GATING and then again ADVISORY in the same invocation —
    doubling the slowest steps in the plan and printing two verdicts for one
    fact. `advisory_plan` already skips a step whose command is identical, which
    is why the floor is applied to `plan` BEFORE the advisory tier is built;
    this pins that ordering rather than the implementation detail.

    IT NEEDS A STEP IN BOTH TABLES TO MEAN ANYTHING (2026-08-21 review, M-8).
    Built over this repo's own profile `held` is EMPTY, so `held + plan` was
    just `plan` and the assertion reduced to "the DevStg-Reqs step table has
    unique names" — a fact about the base table, nothing about the floor.
    Proved by mutation: deleting the dedup guard in `check.floor_plan` left
    this file 5-passed. The fixture below declares a product step at BOTH bars,
    so that guard is the only thing keeping its name from appearing twice."""
    profile = _profile_with(tmp_path, CANARY_BOTH_BARS)

    def steps_at(gate):
        return check.steps("coverage.json", "smoke", gate, None, profile)

    gate = "DevStg-Reqs"
    plan = [s for s in steps_at(gate) if gate in s[3]]
    assert "product-both" in {s[0] for s in plan}, "the fixture step is not in the plan"
    assert "product-both" in {s[0] for s in steps_at("DevStg-Tests")}
    held = check.floor_plan(gate, plan, "DevStg-Tests", steps_at)
    full = held + plan
    names = [s[0] for s in full]
    assert names.count("product-both") == 1, (
        "the floor re-ran a step the gating plan already carries: {}".format(names)
    )
    assert len(names) == len(set(names)), "the floor duplicated a step: {}".format(
        names
    )


def test_the_floor_is_dormant_for_the_BUILT_IN_product_steps_and_says_so():
    """THE HONESTY TRIPWIRE, and the most important test in this file.

    Measured while building the floor, not inherited from the review: OI-30 D2
    CEILINGS `derive_gate.sr_bar` at `DevStg-Tests` — `DevStg-Impl` is
    unreachable from a status cell until the harness driver lands. `ex-draft` is
    a MIN that includes `sr_bar`, so it can never exceed DevStg-Tests either,
    while `format`/`lint`/`tests+coverage` are tagged `{DevStg-Impl}` ONLY.

    So the floor cannot hold the three built-in product checks TODAY, and C-01's
    stated mechanism ("one draft row removes them") is not what is binding for
    them — they were already unreachable from the derived selector, draft or no
    draft, on every push and pull request an adopter runs. Which bar those three
    belong at is a policy question with an owner ruling already sitting on it
    (OI-51); this test exists so nobody reads the floor as having fixed it.

    It fails the day EITHER half moves — the ceiling lifting or the tags
    changing — which is deliberate: `derive_gate`'s ceiling comment says its own
    removal must be "an act rather than a drift", and arming this floor is part
    of that act."""
    assert derive_gate._RELEASE_CEILING == derive_gate.BAR_TESTS, (
        "the release ceiling moved — re-read OI-51 and arm the product floor "
        "deliberately (see this test's docstring)"
    )
    built_in = {"format", "lint", "tests+coverage"}
    tagged = {s[0]: s[3] for s in _steps_at("DevStg-Impl") if s[0] in built_in}
    assert set(tagged) == built_in
    for name, gates in tagged.items():
        assert gates == {check.BAR_RELEASE}, (
            "{} is no longer DevStg-Impl-only: the floor can now hold it, so "
            "OI-51 needs re-reading before this pin is re-stamped".format(name)
        )
    # The consequence, stated as an assertion rather than as a comment: at the
    # highest floor the spine can currently derive, none of the three is held.
    gate = "DevStg-Reqs"
    plan = [s for s in _steps_at(gate) if gate in s[3]]
    held = check.floor_plan(gate, plan, "DevStg-Tests", _steps_at)
    assert not (built_in & {s[0] for s in held})


def test_one_drafted_row_does_not_lose_an_established_product_check(scaffold):
    """THE REGRESSION FIXTURE THE REVIEW ASKS FOR, driven end to end.

    "Start with a mature repository, add one Drafted row, and assert that all
    established product checks remain in the plan." Everything above asserts
    selection against a hand-written basis line; this one makes the PRODUCER
    produce the drop — `derive_gate` reading real registry rows — so a rename of
    the `ex-draft=` field, or a change to how a draft is counted, fails here
    rather than silently disarming the floor (the D-9 basis-rename precedent).

    The product check is a DECLARED `[step:]` at `layer = product`, not one of
    the three built-ins, and that is not a convenience: the built-ins are
    unreachable today (see the dormancy test above), so a fixture using them
    would assert nothing and pass for the wrong reason. An adopter-declared
    product step is the live case, and `docs/stack.ini` is the documented way an
    adopter adds one.

    The process-layer control in the same run is what makes it a two-axis proof
    rather than a "nothing changed" tautology — and what that control does is
    itself a measured correction to this test's first draft, kept because it is
    the more precise claim. `traceability` is NOT lost to the draft: WI-336's
    ratification window already demotes it to the warn-only ADVISORY tier. So
    the two axes are not "kept versus dropped" but **kept AT THE BAR versus
    demoted to advisory**, which is exactly the separation this floor exists to
    draw. Reading only the combined output would have passed a floor that
    promoted everything."""
    docs = scaffold / "docs"
    make_minimal_project(scaffold)
    stack = docs / "stack.ini"
    stack.write_text(
        stack.read_text(encoding="utf-8") + CANARY_PRODUCT, encoding="utf-8"
    )

    def plan_names():
        """(gating, advisory) — split, because `--list` prints both tiers and a
        step demoted to warn-only still appears in the combined text."""
        proc = run_py(["scripts/check.py", "--list", "--tier", "smoke"], cwd=scaffold)
        assert proc.returncode == 0, proc.stdout + proc.stderr
        text = proc.stdout + proc.stderr
        head, sep, tail = text.partition("Advisory during the open")
        return head, (sep + tail)

    def derived():
        proc = run_py([SCRIPTS / "derive_gate.py"], cwd=scaffold)
        assert proc.returncode == 0, proc.stdout + proc.stderr
        return derive_gate.compute(docs)

    # 1. MATURE: a fully decomposed chain reads DevStg-Tests, and both the
    #    declared product step and the process control are in the plan.
    before = derived()
    assert before["gate"] == "DevStg-Tests"
    mature_gating, _mature_advisory = plan_names()
    assert "product-canary" in mature_gating
    assert "traceability" in mature_gating

    # 2. ONE DRAFTED ROW — an ordinary new requirement, nothing else changed.
    srs = docs / "requirements" / "system-requirements.csv"
    srs.write_text(
        srs.read_text(encoding="utf-8")
        + 'SR-002,Subtraction,SN-001,"The system shall subtract.",'
        '"Realizes SN-001.","sub(3,1) == 2",,M,Test,Drafted\n',
        encoding="utf-8",
    )
    after = derived()

    # 3. The bar DROPPED and the ratified evidence HELD. Both halves, or the
    #    fixture is not testing what it claims.
    assert after["gate"] == "DevStg-Reqs", "the draft did not drop the bar"
    assert after["drafted"] == 1
    assert derive_gate.BAR_NAMES[after["ex_draft"]] == "DevStg-Tests", (
        "ex-draft moved with the draft — the floor's whole basis is gone"
    )

    # 4. THE CLAIM: the established product check survives; the maturity check
    #    does not; and the run SAYS why the surviving step is there.
    gating, advisory = plan_names()
    assert "product-canary" in gating, (
        "a single Drafted row removed an established product check:\n" + gating
    )
    assert "Product-regression floor DevStg-Tests" in gating, gating
    # The maturity axis still falls to the same draft — demoted to warn-only,
    # not held at the bar. If the floor ever promotes this it has stopped being
    # a product floor and become a bar that ignores its own derivation.
    assert "traceability" not in gating, (
        "the maturity axis was held at the bar — the floor is overreaching:\n" + gating
    )
    assert "traceability" in advisory, advisory
    # And the promoted step must not ALSO run warn-only: one step, one verdict.
    assert "product-canary" not in advisory, (
        "the floor and the advisory tier both claimed the same step:\n" + advisory
    )
