"""G3-only steps run ADVISORY while a ratification window is open (WI-336).

Owner ruling 2026-07-27, made on measured cost: an open `Draft`/`Modified`
window drops the derived gate, and the plan then drops every step tagged for the
higher gate — so `lint`, `dupes` and `--require-verified` STOP RUNNING. That is
a blind spot, not a lower bar. Twelve commits went green over those steps during
the 2026-07-26/27 window; 20 ruff findings and 86 duplicate blocks surfaced in
one lump when it closed (WI-333 / WI-334).

The trigger is deliberately narrow, and these guards pin that: the steps run
advisory only when the gate was **suppressed by a window**, which
`derive_gate.py` records as `drafts=`/`modified=` in the `# basis:` comment. A
project genuinely at G1 has not earned those steps and must not be nagged by
them on every run — a warn tier nobody wants is a warn tier everybody learns to
ignore.
"""

import re

from conftest import ROOT, SCRIPTS, load_script, run_py

check = load_script("check")

GATE_WINDOW = """\
# DERIVED GATE — generated by scripts/derive_gate.py (do not hand-edit).
# basis: SN=1 SR=2 LLR=2 TC=2 drafts=0 modified=7 computed=G2 phase=1
G2
"""
GATE_DRAFT = GATE_WINDOW.replace("drafts=0 modified=7", "drafts=3 modified=0")
GATE_CLEAN = GATE_WINDOW.replace("drafts=0 modified=7", "drafts=0 modified=0")
GATE_HAND_WRITTEN = "# a hand-maintained gate file, no derivation basis\nG2\n"


def _gate(tmp_path, text, name="gate"):
    p = tmp_path / name
    p.write_text(text, encoding="utf-8")
    return p


def test_window_open_detects_either_kind_of_pending_row(tmp_path):
    assert check.window_open(_gate(tmp_path, GATE_WINDOW, "a")) is True
    assert check.window_open(_gate(tmp_path, GATE_DRAFT, "b")) is True
    # The negative halves, which are the whole point of the narrow trigger:
    # a settled spine gets no advisory pass...
    assert check.window_open(_gate(tmp_path, GATE_CLEAN, "c")) is False
    # ...a gate file with no derivation basis expresses NO opinion rather than
    # guessing (a hand-maintained or pre-derived file must not start nagging)...
    assert check.window_open(_gate(tmp_path, GATE_HAND_WRITTEN, "d")) is False
    # ...and a repo with no gate file at all is not a window.
    assert check.window_open(tmp_path / "does-not-exist") is False


def test_advisory_steps_are_the_higher_gates_and_never_the_current_one():
    """The selection rule itself, over the real step table.

    Asserts the SHAPE the ruling asked for: at G2 with a window, the advisory
    set is exactly the steps G2 does not require but a higher gate does — and it
    never contains a step already in the gating plan, which would run it twice
    and report it twice."""
    # The REAL profile: `dupes` is a docs/stack.ini `[step:]`, so a None profile
    # would silently drop it and this guard would assert against a smaller table
    # than the harness actually runs.
    profile = check.load_profile(ROOT / "docs" / "stack.ini")
    all_steps = check.steps(80, "all", "G2", None, profile)
    plan = [s for s in all_steps if "G2" in s[3]]
    # Call `advisory_plan` rather than restating its filter. The first version of
    # this test re-implemented the selection rule, so it asserted against its own
    # copy and would have passed against any implementation — the same
    # cannot-observe-what-it-names shape as the other vacuous guards this session
    # produced. `window_open` is patched because the real repo has no open
    # window, and the SELECTION is what is under test here, not the trigger.
    real_window_open = check.window_open
    check.window_open = lambda *a, **k: True
    try:
        advisory = check.advisory_plan(all_steps, "G2")
    finally:
        check.window_open = real_window_open
    plan_names = {s[0] for s in plan}
    advisory_names = {s[0] for s in advisory}

    # The three steps the ruling was about are exactly the ones recovered.
    assert {"lint", "dupes"} <= advisory_names, advisory_names
    # `--require-verified` rides the `traceability` step's G3 variant; the G3
    # criterion is what the owner ruled should also surface, so assert the
    # advisory set is non-trivial rather than pinning an implementation name.
    assert len(advisory_names) >= 3, advisory_names
    # The exclusion asserted as BEHAVIOUR, not as a constant. Asserting only
    # `"tests+coverage" in ADVISORY_EXCLUDE` passes even when the filter ignores
    # the set entirely — proven by mutation: deleting the `not in
    # ADVISORY_EXCLUDE` clause left every other assertion here green.
    assert "tests+coverage" not in advisory_names, advisory_names
    # The negative half: no step is both gating and advisory.
    assert not (plan_names & advisory_names), plan_names & advisory_names
    # ...and nothing G2 already requires got demoted into the warn tier.
    assert "traceability" in plan_names and "traceability" not in advisory_names


def test_advisory_output_is_marked_as_not_gating(tmp_path):
    """A warn tier that prints a bare `FAIL` is how a non-gating step gets read
    as the bar. The summary line must say so on the same line."""
    source = (SCRIPTS / "check.py").read_text(encoding="utf-8")
    assert "[advisory — not gating]" in source
    # ...and the banner must state the exit code is unaffected, because that is
    # the claim a reader needs before they decide to ignore a line.
    assert "the exit code is not affected" in source


def test_the_expensive_step_is_excluded_and_says_why():
    """`tests+coverage` must NOT join the advisory pass.

    It is the one G3 step that is not a blind spot — the commit bar runs the
    suite directly — and including it would re-run the whole suite plus coverage
    on every gate run for the life of a window (measured 55.8 s at the smoke
    tier, ~11 min unfiltered). A warn tier that doubles every run is one people
    route around, which costs more than it catches.

    Pinned by name because an exclusion is a hole in the coverage this ruling
    just created: if a future edit drops the reason, this fails and the next
    author has to restate it."""
    assert "tests+coverage" in check.ADVISORY_EXCLUDE
    source = (SCRIPTS / "check.py").read_text(encoding="utf-8")
    assert "is NOT a blind spot" in source
    # The negative half: the exclusion list is a scalpel, not a bucket — the
    # steps the ruling was actually about must never be in it.
    assert not ({"lint", "dupes"} & check.ADVISORY_EXCLUDE)


WINDOW_GATE = (
    "# DERIVED GATE — generated by scripts/derive_gate.py\n"
    "# basis: SN=1 SR=1 LLR=1 TC=1 drafts=0 modified={} computed=G2 phase=1\n"
    "G2\n"
)
CANARY_STEP = (
    "\n[step:always-fails]\n"
    "command = {py} -c \"import sys; print('ADVISORY-CANARY'); sys.exit(1)\"\n"
    "gates = G3\n"
)


def test_an_advisory_failure_does_not_change_the_exit_code(scaffold):
    """The load-bearing claim, driven end to end.

    Everything above asserts selection and wording. This asserts the ONE thing
    the ruling promises: a step that FAILS in the advisory pass is reported and
    does not change the run's outcome. "Warn-only" is a property of the exit
    code, and no amount of string-matching in the source can observe it.

    Measures the GATING FAILURE COUNT, not just the exit code: a bare scaffold
    is not green at G2 (it fails derived-gate/traceability/design-flows on
    placeholder registries), so `exit 0` would be testing the fixture and
    exit-code EQUALITY is blind — 1 == 1 whether or not the advisory step
    gated. The count moves the moment an advisory failure is counted as a real
    one, which is precisely the regression this guards. Verified by mutation:
    letting `advisory_results` feed `failed` takes it 3 -> 4."""
    docs = scaffold / "docs"
    (docs / "gate").write_text(WINDOW_GATE.format(4), encoding="utf-8")
    args = ["scripts/check.py", "--gate", "G2", "--tier", "smoke"]

    def gating_failures(proc):
        text = proc.stdout + proc.stderr
        m = re.search(r"RESULT: FAIL \((\d+) step\(s\) failed\)", text)
        return int(m.group(1)) if m else 0  # PASS = zero gating failures

    baseline = run_py(args, cwd=scaffold)

    stack = (docs / "stack.ini").read_text(encoding="utf-8")
    (docs / "stack.ini").write_text(stack + CANARY_STEP, encoding="utf-8")
    withcanary = run_py(args, cwd=scaffold)
    out = withcanary.stdout + withcanary.stderr

    assert "ADVISORY-CANARY" in out, "the advisory step never ran:\n" + out
    assert "advisory — not gating" in out, out
    assert gating_failures(withcanary) == gating_failures(baseline), (
        "a FAILING advisory step was counted as a gating failure ({} -> {}):"
        "\n{}".format(gating_failures(baseline), gating_failures(withcanary), out)
    )
    assert withcanary.returncode == baseline.returncode, out

    # The negative half: close the window and that same failing step must vanish
    # entirely — not run, not reported — or this is a permanent warn tier rather
    # than a window-scoped one.
    (docs / "gate").write_text(WINDOW_GATE.format(0), encoding="utf-8")
    closed = run_py(args, cwd=scaffold)
    assert "ADVISORY-CANARY" not in (closed.stdout + closed.stderr)
